#! /bin/bash


myuser=$USER

function createDB {

     read -p "Enter Database name : "  -t 10  name
    
      pattern="^[a-zA-Z]+"
        
          if  [[  "$name" =~ $pattern &&  -n $name  ]];then

               for i in `ls  /home/$myuser/database-engine-in-bash/DataBases/`
                do
                  echo $i
                  if [[ $i != $name ]];then 
                        existed="false"
                   else
                        existed="true"
                        break
                   fi
                done 
              
            if [[ $existed =  "false" ]];then 
               mkdir /home/$myuser/database-engine-in-bash/DataBases/$name
        
              if [[ $? -eq 0 ]] ;then
               echo "$name has created"
               fi

             else
                echo "the $name databse is  already existed"
               fi
          else

              echo " kindly start database name with letter [a-z] or [A-Z] "
            fi
 }



function listDB {

           test_database=`ls /home/$myuser/database-engine-in-bash/DataBases/ `
     
              if [[ -n $test_database ]] ;then
              
                ls  /home/$myuser/database-engine-in-bash/DataBases/
              
              else

                echo 'no databases has found'
               
               fi
 }




select var in "Create DB" "list DB"  "Connect DB"  "Drop DB" "Exit"
do 

 if [[ $REPLY =~ ^[1-5]$ && -n $REPLY ]] ;then

     case $REPLY in 

     1) 
         echo "hello from create fn"
          createDB  
         ;;


     2)
         echo "hello from list fn"
         listDB
         ;;

     3)
         echo "hello from connect fn"
         #connectDB
         ;;

     4)
          echo "hello from drop fn"
         #dropDB
         ;;
     5)
        exit
        ;;

     esac
  else
   echo "please enter valid number"
  fi

done 
