name: CI

on:
  push:
    branches:
      - main  # Replace 'main' with the name of your main branch if it's different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bash
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run manual tests
        run: |
          chmod +x unit_tests/test_create_db.sh
          chmod +x unit_tests/test_drop_db.sh
          ./unit_tests/test_create_db.sh
          ./unit_tests/test_drop_db.sh
          

